<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="P_Unit_Tests" Id="{08c39198-6e34-4947-81d5-6830d7c1050c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Unit_Tests
VAR
	fbFoo_Tests		:	FB_Foo_Tests;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbFoo_Tests();




]]></ST>
    </Implementation>
    <LineIds Name="P_Unit_Tests">
      <LineId Id="99" Count="0" />
      <LineId Id="104" Count="3" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>